### ISSUE TITLE
Clone Problem

### ISSUE THREAD

**Issue by WadeWong7** [AAU-CNT/efficient-ris-aided-urllc#1]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/aau-cnt/efficient-ris-aided-urllc.git/info/lfs'

**Comment by lostinafro** [comment]
Hi,

the problem is given by the fact that your machine has not the LFS installed. Please, check the readme.md and try to install LFS extension to manage large file.
Ask to re-open the issue if the problem is not solved.

Kind regards
